---
all:
  children:
    dspace:
      hosts:
        dspace-server:
          ansible_host: 192.168.100.88
          ansible_user: ubuntu
          ansible_become: true
          ansible_become_method: sudo
          ansible_ssh_private_key_file: ~/.ssh/id_rsa

          # For localhost (install on the control machine itself):
          # ansible_connection: local
          # ansible_user: "{{ ansible_env.USER }}"
