---
dspace_src_tarball_url: "https://github.com/DSpace/DSpace/releases/download/dspace-{{ dspace_version }}/dspace-{{ dspace_version }}-src-release.tar.gz"
dspace_src_tarball_dest: "{{ dspace_build_dir }}/dspace-{{ dspace_version }}-src-release.tar.gz"
dspace_src_dir: "{{ dspace_build_dir }}/dspace-{{ dspace_version }}-src-release"
dspace_installer_dir: "{{ dspace_src_dir }}/dspace/target/dspace-installer"
dspace_backend_port: 8080
dspace_system_user: "dspace"
dspace_system_group: "dspace"

# Maven build options — tests are off by default in DSpace's own Maven config
maven_opts: "--batch-mode package -DskipTests -Dlicense.skip=true"
